In [3]:
import torch
import torch.backends.cudnn as cudnn
import torch.nn.functional as F
import torch.nn as nn

import numpy as np
import sys
import os
import pdb
from PIL import Image

from myloss import weighted_binary_cross_entropy
from validation import validate

In [8]:
c = nn.BCELoss(size_average=True, reduce=True)

TypeError: __init__() got an unexpected keyword argument 'reduce'

In [7]:
c

BCELoss(
)

In [96]:
input = np.zeros((3, 3))
input = np.arange(9).reshape((3, 3)) / 8
input = np.random.uniform(size=(3, 3))
print(input)
target = np.ones((3, 3))
print(target)
input = torch.FloatTensor(input)
target = torch.FloatTensor(target)
input = Variable(input)
target = Variable(target)
c = F.binary_cross_entropy(input, target)

[[0.71620794 0.33709557 0.72499019]
 [0.33177587 0.3925606  0.29548292]
 [0.99424769 0.44564739 0.06238164]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [97]:
c

Variable containing:
 0.9543
[torch.FloatTensor of size 1]

In [98]:
eps = 0.000000000001
loss = (target * (input + eps).log() + (1. - target) * (1. - input + eps).log()) * (-1.)

In [99]:
loss

Variable containing:
 0.3338  1.0874  0.3216
 1.1033  0.9351  1.2191
 0.0058  0.8082  2.7745
[torch.FloatTensor of size 3x3]

In [100]:
loss.mean()

Variable containing:
 0.9543
[torch.FloatTensor of size 1]